In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\grbar\appdata\local\python\pythoncore-3.12-64\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\grbar\appdata\local\python\pythoncore-3.12-64\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\grbar\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\grbar\appdata\local\python\pythoncore-3.12-64\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\grbar\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [12]:
df = pd.read_csv('C:\\Dev\\Zoomcamp\\final-project\\VRA_202510.csv', sep=';', skiprows=1)

In [13]:
df.head(5)

,ICAO Empresa Aérea,Número Voo,Código Autorização (DI),Código Tipo Linha,ICAO Aeródromo Origem,ICAO Aeródromo Destino,Partida Prevista,Partida Real,Chegada Prevista,Chegada Real,Situação Voo,Código Justificativa
0,LPE,2423,0,I,SBPA,SPJC,2025-10-23 07:20:00,2025-10-23 07:12:00,2025-10-23 12:25:00,2025-10-23 12:18:00,REALIZADO,NaN
1,LPE,2423,0,I,SBPA,SPJC,2025-10-25 07:20:00,2025-10-25 07:14:00,2025-10-25 12:25:00,2025-10-25 12:19:00,REALIZADO,NaN
2,LPE,2423,0,I,SBPA,SPJC,2025-10-27 07:45:00,2025-10-27 07:32:00,2025-10-27 12:25:00,2025-10-27 12:54:00,REALIZADO,NaN
3,LPE,2423,0,I,SBPA,SPJC,2025-10-30 07:45:00,2025-10-30 07:35:00,2025-10-30 12:25:00,2025-10-30 13:16:00,REALIZADO,NaN
4,LPE,2428,0,I,SPJC,SBGR,2025-10-01 01:15:00,2025-10-01 01:12:00,2025-10-01 06:15:00,2025-10-01 06:33:00,REALIZADO,NaN

In [15]:
len(df)

85828

In [14]:
df[df['Situação Voo']=='CANCELADO']

,ICAO Empresa Aérea,Número Voo,Código Autorização (DI),Código Tipo Linha,ICAO Aeródromo Origem,ICAO Aeródromo Destino,Partida Prevista,Partida Real,Chegada Prevista,Chegada Real,Situação Voo,Código Justificativa
67135,LCO,3613,0,G,GVAC,SBKP,2025-10-01 17:30:00.100000000,NaN,2025-10-02 00:00:00.100000000,NaN,CANCELADO,NaN
69496,1ED,1234,0,I,MMUN,MDPC,2025-10-01 16:00:00.100000000,NaN,2025-10-01 20:00:00.100000000,NaN,CANCELADO,NaN
69497,1ED,1234,0,I,SAEZ,MMUN,2025-10-01 07:00:00.100000000,NaN,2025-10-01 15:00:00.100000000,NaN,CANCELADO,NaN
69498,ACN,5444,0,N,SBCT,SSVL,2025-10-01 09:10:00,NaN,2025-10-01 10:20:00,NaN,CANCELADO,NaN
69499,ACN,5445,0,N,SSVL,SBCT,2025-10-01 10:45:00,NaN,2025-10-01 11:45:00,NaN,CANCELADO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
77054,TAM,3911,0,N,SBRJ,SBSP,2025-10-31 08:25:00,NaN,2025-10-31 09:35:00,NaN,CANCELADO,NaN
77055,TAM,3920,0,N,SBSP,SBRJ,2025-10-31 16:00:00,NaN,2025-10-31 17:00:00,NaN,CANCELADO,NaN
77056,TAM,3935,0,N,SBRJ,SBSP,2025-10-31 15:15:00,NaN,2025-10-31 16:20:00,NaN,CANCELADO,NaN
77057,TAM,4526,0,N,SBPA,SBGR,2025-10-31 20:10:00,NaN,2025-10-31 22:00:00,NaN,CANCELADO,NaN
77058,TAP,0075,0,I,LPPT,SBGL,2025-10-31 20:25:00,NaN,2025-11-01 06:30:00,NaN,CANCELADO,NaN

In [22]:
df['ICAO Aeródromo Origem'].value_counts()

ICAO Aeródromo Origem
SBGR    12614
SBSP     8237
SBGL     5352
SBKP     5316
SBBR     5238
        ...
SKCC        1
DGAA        1
GCTS        1
SBBP        1
KTPA        1
Name: count, Length: 243, dtype: int64

In [23]:
aero_publicos['CÓDIGO OACI'].value_counts()

CÓDIGO OACI
SBAA    1
SBAE    1
SBAQ    1
SBAR    1
SBAT    1
       ..
SBPW    1
SSBG    1
SND4    1
SND6    1
SD5Q    1
Name: count, Length: 501, dtype: int64

In [19]:
aero_publicos = pd.read_csv('C:\\Dev\\Zoomcamp\\final-project\\cadastro-de-aerodromos-civis-publicos.csv', sep=';', skiprows=1, on_bad_lines='skip', engine='python')

In [20]:
aero_publicos.head(5)

,CÓDIGO OACI,CIAD,NOME,MUNICÍPIO ATENDIDO,UF,LATITUDE,LONGITUDE,ALTITUDE,OPERAÇÃO,OACI,...,CAT SESCINC,r1,r2,REFERÊNCIA(S),RESTRIÇÃO(ÕES),SITUAÇÃO,r1.1,REFERÊNCIA,SITUADO NA AMAZÔNIA LEGAL,OBSERVAÇÕES
0,SBAA,PA0008,CONCEIÇÃO DO ARAGUAIA,CONCEIÇÃO DO ARAGUAIA,PA,8° 20' 55'' S,49° 18' 11'' W,199 m,VFR Diurno/Noturno e IFR Diurno,-,...,0,-,-,-,-,Proibição de operações de pouso de aeronaves d...,PA2019-1362,PA2019-1362,X,-
1,SBAE,SP0010,BAURU/AREALVA,BAURU,SP,22° 9' 28'' S,49° 4' 6'' W,598 m,VFR Diurno/Noturno e IFR Diurno/Noturno,-,...,0,-,-,-,-,-,-,-,NaN,-
2,SBAQ,SP0012,BARTOLOMEU DE GUSMÃO,ARARAQUARA,SP,21° 48' 43'' S,48° 7' 59'' W,711 m,VFR Diurno/Noturno e IFR Diurno/Noturno,-,...,0,-,-,-,-,-,-,-,NaN,-
3,SBAR,SE0001,SANTA MARIA,ARACAJU,SE,10° 59' 7'' S,37° 4' 24'' W,7 m,VFR Diurno/Noturno e IFR Diurno/Noturno,RS,...,7,PA2022-7303,-,PA2022-7303,-,-,-,-,NaN,-
4,SBAT,MT0003,PILOTO OSVALDO MARQUES DIAS,ALTA FLORESTA,MT,9° 51' 59'' S,56° 6' 18'' W,289 m,VFR Diurno/Noturno e IFR Diurno/Noturno,-,...,0,-,-,-,-,-,-,-,X,-

In [8]:
aero_privados = pd.read_csv(r'C:\Dev\Zoomcamp\final-project\data\raw\AerodromosPrivados.csv', encoding='latin-1', sep=';', skiprows=1)

In [5]:
aero_publicos = pd.read_csv(r'C:\Dev\Zoomcamp\final-project\data\raw\AerodromosPublicos.csv', encoding='latin-1', sep=';', skiprows=1)

In [6]:
aero_publicos.head(5)

,Código OACI,CIAD,Nome,Município,UF,Município Servido,UF Servido,LATGEOPOINT,LONGEOPOINT,Latitude,Longitude,Altitude,Operação Diurna,Operação Noturna,Situação,Validade do Registro,Portaria de Registro,Link Portaria
0,SDZG,CE0008,Pedro Teixeira Castelo Regional Tauá,TAUÁ,Ceará,Tauá,Ceará,-5.933333,-40.297500,"05°56'00""S","040°17'51""W","444,0",VFR,VFR,Cadastrado,07/05/2030,PA2020-1189,https://pergamum.anac.gov.br/arquivos/PA2020-1...
1,SDIG,SP0038,Ibitinga,IBITINGA,São Paulo,Ibitinga,São Paulo,-21.747222,-48.855833,"21°44'50""S","048°51'21""W","542,0",VFR,Sem Operação,Cadastrado,23/04/2030,PA2020-1074,https://pergamum.anac.gov.br/arquivos/PA2020-1...
2,SBVT,ES0001,Eurico de Aguiar Salles,VITÓRIA,Espírito Santo,Vitória,Espírito Santo,-20.258056,-40.286389,"20°15'29""S","040°17'11""W","3,0",VFR / IFR - CAT I,VFR / IFR - CAT I,Cadastrado,NaN,NaN,NaN
3,SNJK,BA0047,Jequié,JEQUIÉ,Bahia,Jequié,Bahia,-13.877778,-40.071389,"13°52'40""S","040°04'17""W","197,0",NaN,NaN,Cadastrado,18/11/2024,PA2014-2695,https://pergamum.anac.gov.br/arquivos/PA2014-2...
4,SSKU,SC0016,Lauro Antônio da Costa,CURITIBANOS,Santa Catarina,Curitibanos,Santa Catarina,-27.287222,-50.603889,"27°17'14""S","050°36'14""W","978,0",VFR,VFR,Cadastrado,20/05/2030,PA2020-1296,https://pergamum.anac.gov.br/arquivos/PA2020-1...

In [4]:
aero_privados.head(5)

,Código OACI,CIAD,Nome,Município,UF,Longitude,Latitude,Altitude,Operação Diurna,Operação Noturna,...,Superfície 1,Designação 2,Comprimento 2,Largura 2,Resistência 2,Superfície 2,Portaria de Registro,Link Portaria,LATGEOPOINT,LONGEOPOINT
0,SN8C,MS0728,Fazenda Maria,CARACOL,MS,"057°07'21""W","22°05'43""S",",0",VFR,Sem Operação,...,Grama,NaN,NaN,NaN,NaN,NaN,PA2024-13.264,https://pergamum.anac.gov.br/arquivos/PA2024-1...,"-22,095278","-57,1225"
1,SIF9,TO0134,Fazenda Rios,BRASILÂNDIA DO TOCANTINS,TO,"048°29'15""W","08°21'08""S",",0",VFR,Sem Operação,...,Piçarra,NaN,NaN,NaN,NaN,NaN,PA2024-13.492,https://pergamum.anac.gov.br/arquivos/PA2024-1...,"-8,3522222","-48,4875"
2,SDX4,PI0093,Canto do Buriti,CANTO DO BURITI,PI,"042°59'24,65""W","08°07'34,62""S","292,0",VFR,Sem Operação,...,Asfalto,NaN,NaN,NaN,NaN,NaN,PA2025-16.710,https://pergamum.anac.gov.br/arquivos/PA2025-1...,"-8,1261111","-42,99"
3,SIS8,RR0153,Fazenda Belo Horizonte,AMAJARI,RR,"061°24'18,05""W","03°32'39,84""N","121,0",VFR,Sem Operação,...,Cascalho,NaN,NaN,NaN,NaN,NaN,PA2024-13.750,https://pergamum.anac.gov.br/arquivos/PA2024-1...,"3,54416667","-61,405"
4,SIVO,MT0142,Fazenda Malu,BOM JESUS DO ARAGUAIA,MT,"051°46'27""W","12°26'53""S","356,0",VFR,Sem Operação,...,Asfalto,NaN,NaN,NaN,NaN,NaN,PA2024-13.687,https://pergamum.anac.gov.br/arquivos/PA2024-1...,"-12,448056","-51,774167"

In [15]:
pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import xlrd

In [22]:
empresas = pd.read_excel(r'C:\Dev\Zoomcamp\final-project\data\raw\glossario_de_empresas_aereas.xls',skiprows=3)

In [25]:
empresas[empresas['Sigla OACI'] == 'ARE']

,Unnamed: 0,Sigla OACI,Nome Empresas,Unnamed: 3,Nacional ou Estrangeira
14,NaN,ARE,AIRES AEROVIAS DE INTEGRACION,NaN,ESTRANGEIRA